### PR TITLE
Add authentication name

### PR DESCRIPTION
**Pull request by iHunt101**
It will be usefull if user uses deferent aside from WPA.

### CODE REVIEW

**Comment by MPX4132** [comment]
WEP verification will fail, the authenticators only deal with WPA/WPA2.

**Comment by deltaxflux** [comment]
I disagree with that.

**Comment by MPX4132** [comment]
@deltaxflux Oh my bad, I just remembered we're not using hashcat, lol.

**Comment by MPX4132** [comment]
Have you tried verifying a WEP capture? I've never tried that, but it seems like it might fail when the user is asked to input a path to the handshake. It might fail at the verification step, is what I mean.

**Comment by deltaxflux** [comment]
Yeah I did it. The output is the same so it (hopefully) doesn't matter.

**Comment by MPX4132** [comment]
Oh ok, nice, thanks for checking.

**Comment by iHunt101** [comment]
Thanks guys!

**Pull request merged**
